{% set name = "amityping" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5f5988a368d0f21022a118bfd140da6f73871792abc8476c809aa4b64b0d9938

build:
  skip: True  # [win]
  noarch: python 
  number: 11
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - mypy_extensions

about:
  home: https://github.com/slac-lcls/amityping
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Type hints for LCLS-II software'
  description: |
    provides typing hints to be shared between LCLS-II analysis packages.
  doc_url: https://github.com/slac-lcls/amityping
  dev_url: https://github.com/slac-lcls/amityping

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

